version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    command:
      [
        "sh", "-c",
        "mkdir -p /etc/mysql/conf.d && \
        echo '[mysqld]' > /etc/mysql/conf.d/timezone.cnf && \
        echo 'default-time-zone = \"+09:00\"' >> /etc/mysql/conf.d/timezone.cnf && \
        exec mysqld --defaults-extra-file=/etc/mysql/conf.d/timezone.cnf"
      ]

    volumes:
      - db_data:/var/lib/mysql
    networks:
      project-network:
        aliases:
          - database
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      project-network:
        aliases:
          - mongodb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms1g -Xmx2g

    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_plugins:/usr/share/elasticsearch/plugins
    networks:
      - project-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - project-network

networks:
  project-network:
    external: true

volumes:
  db_data:
  mongo_data:
  redis_data:
  elasticsearch_data:
  elasticsearch_plugins:

